#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic hook:     chroot_post_build_BUILDSTEP
# called by:	uic_build
#
# This hook will be called by uic_build in the chrooted installation
# environment in $TARGET after performing a BUILDSTEP build procedure.
# This file is only a template. The file MUST be named based on the
# build procedure (e.g. chroot_pre_build_initrd for initrd build procedure)
