#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic chroot hook:	chroot_post_customization
# called by:		uic_create, uic_build
#
# This hook will be called by several command in the chrooted installation
# environment in $TARGET after making all customizations (file copies and
# deletions) to the installation environment in $TARGET
# Since this hook runs in chroot, none of the internal UIC variables are
# available.
