#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic chroot hook:	chroot_pre_installation
# called by:		uic_create, uic_update
#
# This hook will be called by uic_create in the chrooted installation
# environment in ${TARGET} before making any software installation and
# configuration steps. Since this hook runs in chroot, none of the
# internal UIC variables are available.
