#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic hook:	post_build
# called by:	uic_build
#
# This hook will be called by uic_build after performing the last build
# step of the build procedure in the installation environment in $TARGET
