#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic hook:	pre_customization
# called by:	uic_create, uic_build
#
# This hook will be called by several commands before making any customizations
# (file copies and deletions) to the installation environment in $TARGET
