#!/bin/bash
#
# (c) 2012 YeaSoft Int'l - Leo Moll
#
# uic hook:	pre_build
# called by:	uic_build
#
# This hook will be called by uic_build before performing the first build
# step of the build procedure in the installation environment in $TARGET
